### PR TITLE
CI: checked db setup

### PR DESCRIPTION
**Pull request by araslanov-e**

### CODE REVIEW

**Comment by araslanov-e** [comment]
#42

**Comment by Mehonoshin** [comment]
@araslanov-e can we see an example of the build, when the seeds are failing?
You can modify seeds on purpose to fail the check for demo purpose.

**Comment by araslanov-e** [comment]
@Mehonoshin will be can use methods with `!` for raise errors?

**Comment by araslanov-e** [comment]
@Mehonoshin added `Option.create!(name: 'fail_option')` for example, and build is fail 
https://travis-ci.org/Mehonoshin/smartvpn-billing/jobs/481226723#L707

**Comment by Mehonoshin** [comment]
Rebase please

**Comment by araslanov-e** [comment]
@Mehonoshin done!

**Comment by araslanov-e** [comment]
I can squash into one commit

**Pull request merged**
